# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MT.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 546)
        MainWindow.setMinimumSize(QtCore.QSize(672, 546))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0.148615 rgba(124, 48, 164, 255), stop:1 rgba(151, 255, 113, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(40, 140, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 4, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.make_plot_button = QtWidgets.QPushButton(self.centralwidget)
        self.make_plot_button.setGeometry(QtCore.QRect(360, 380, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.make_plot_button.setFont(font)
        self.make_plot_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.make_plot_button.setObjectName("make_plot_button")
        self.lineEdit_for_high = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_for_high.setGeometry(QtCore.QRect(40, 410, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_for_high.setFont(font)
        self.lineEdit_for_high.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.lineEdit_for_high.setObjectName("lineEdit_for_high")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.label_4.setScaledContents(True)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 90, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 140, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 140, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.003, y1:1, x2:0.991, y2:0.015194, stop:0.158324 rgba(163, 119, 163, 255), stop:0.538999 rgba(143, 175, 218, 255), stop:1 rgba(226, 214, 255, 255))")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 250, 591, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "МРТ-5 построение графиков"))
        self.label.setText(_translate("MainWindow", "Выберите дату"))
        self.make_plot_button.setText(_translate("MainWindow", "Создать график"))
        self.lineEdit_for_high.setText(_translate("MainWindow", "50, 150"))
        self.label_4.setText(_translate("MainWindow", "Введите одну или несколько высот\n"
" через запятую (0-1000 с шагом 50)"))
        self.label_2.setText(_translate("MainWindow", "Укажите размер графика в дюймах"))
        self.lineEdit.setText(_translate("MainWindow", "20"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "x"))
        self.lineEdit_2.setText(_translate("MainWindow", "10"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "y"))
        self.lineEdit_3.setText(_translate("MainWindow", "C:\\Users\\kirit\\Downloads\\archive\\"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
